apiVersion: v1
kind: Service
metadata:
  name: flask-leader
  labels:
    app: flask
    role: leader
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: flask
    role: leader
    tier: backend
