apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gke-test-service
  annotations:
    kubernetes.io/ingress.global-static-ip-name: url-shortener-app-cs6620
spec:
  backend:
    serviceName: gke-test-service
    servicePort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gke-test-service
spec:
  type: NodePort
  selector:
    app: gke-test
  ports:
  - port: 80
    targetPort: 5000
